### ISSUE TITLE
Проблемы построения языка

### ISSUE THREAD

**Issue by HumsterProgrammer** [BaldiSlayer/rofl-lab2#2]
Немного не понимаю как можно построить регулярный язык, который разбирает последовательность команд

Пусть алфавит Σ ={l, r, u, d} и мы имеем простой лабиринт 3×3: (*)

```
###
#S+
###
```

, где # - непустая клетка, + - пустая клетка, S - старт, F - финиш

Если агент(так буду называть того, кто проходит лабиринт) дошел до финиша по командам, то последовательность команд принадлежит языку.

Дополнительно условия:
- если команда не может быть выполнена(например, u, но сверху не пустая клетка), то агент остается на месте. В автомате можно это представить как переход q->q.
- агент может выйти за пределы лабиринта, и ходить там сколько угодно(что также будет будет принадлежать языку), но если он зайдет обратно, то уже команды не будут принадлежать языку.

Сначала по первому условию.
Для лабиринта (*) может подойти следующая регулярка

(L | U | D)* R ( U | D | L (U | D | L)* R)* R

Но она не будет соответствовать языку.

Получается язык не регулярен? 

Регулярен. Вот автомат:

![20241009_125001.jpg](https://github.com/user-attachments/assets/c724138e-b1e1-4433-a723-69557ac98636)

Такой автомат неплохо разбирает, но не справляется с внешней частью. 

Резюмирую. Проблемы следующие:
+ Какой тип языка команд? Регулярен ли он?
+ Как построить автомат, разбирающий язык?
+ Как построить его классы эквивалентности?

**Comment by HumsterProgrammer** [comment]
P.S. простите за корявый рисунок. На телефоне лучше не получилось

**Comment by HumsterProgrammer** [comment]
_Гипотеза 1_

Язык состоит из конкатенации двух языков {L1 L2}, где L1 - язык прохождения лабиринта, L2 - язык брождения вне лабиринта, причем L2 включает в себя слова, в которых мы заходим внутрь лабиринта, но выходим обратно

**Comment by HumsterProgrammer** [comment]
Update условия. 

Агент стартует из западной и северной клетки.
Агент принимает команды из алфавита {W, S, N, E}

Пусть лабиринт ограничен 4×4 стеной

```
######
#S+++#
#++++#
#+++++
#++++#
######
```

Пример простого лабиринта.
Пример строки которая выводит из лабиринта: SSEEEE
Пример "страшной" строки, которая выводит из лабиринта: WWEWEENNSSEEEEWEN

**Comment by HumsterProgrammer** [comment]
Кажется, я не правильно понял суть задания

**Comment by TonitaN** [comment]
Могут быть непроходимые клетки, значит, например, лабиринт может содержать клетку, в которую невозможно попасть. При этом клетка считается сплошной стеной (то есть нет недостижимых из угловой комнаты комнат и коридоров лабиринта, иначе его невозможно восстановить по путям в нём из этой клетки, но не обязательно комнаты и проходы заполняют весь прямоугольник M*N).
